services:
  db:
    image: postgres:16
    container_name: banking_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-default}
      POSTGRES_DB: ${DB_NAME:-default_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge